version: '3.9'
services:
  db:
    ports:
      - '5432:5432'
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    container_name: db_postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - igs_network
networks:
  igs_network:
    driver: bridge
