version: '3.9'
services:
  db:
    build: ./api/
    ports:
      - 5432:5432
    container_name: db_postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - igs_network
networks:
  igs_network:
    driver: bridge
