FROM postgres

# Set the environment variables
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=db_employee

# Create a volume to store the database
VOLUME /var/lib/postgresql/data