# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Django API

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env: 
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORES_VIRTUALENVS: 1
    runs-on: ubuntu-latest
    
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7.1, 3.8.1, 3.9.1, 3.10.0]
    
    services: 
      postgres:
        image: postgres
        env: 
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: "5432:5432"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.0
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Preparing server
      run: sudo apt-get update
    - name: Preparing server to python
      run: |
        sudo apt-get install -y build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm gettext libncurses5-dev tk-dev tcl-dev blt-dev libgdbm-dev git python-dev python3-dev aria2 vim libnss3-tools python3-venv liblzma-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Copying env var configuration
      run: |
        sudo cp contrib/env-sample .env
    - name: Validate PEP8
      run: |
        flake8
    # - name: Test with pytest
    #   run: |
    #     pytest --cov=api
    #     pytest --cov=core